language: node_js
node_js:
  - "6.11.0"

env:
  global:
    - SAUCE_USERNAME="$SAUCE_DEV_NAME"
    - SAUCE_ACCESS_KEY="$SAUCE_DEV_KEY"
    - CODACY_PROJECT_TOKEN="$CODACY_TOKEN"
    - COVERALLS_REPO_TOKEN="$COVERALLS_MOJS_TOKEN"

script:
  - npm run lint
  - npm run test

after_script:
  - cat ./coverage/lcov-report/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov-report/lcov.info | ./node_modules/.bin/codacy-coverage

notifications:
    slack: mojs:pdoYLMGz4fOmYH7mzpXAGVjn
